# Generated by Django 5.1.1 on 2024-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("grocery_store", "Grocery Store"),
                    ("food_pantry", "Food Pantry"),
                    ("self", "Self"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
