# Generated by Django 5.1.1 on 2024-10-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("database", "0002_alter_organization_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender_id",
        ),
        migrations.RemoveField(
            model_name="userreview",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="organizationadmin",
            name="user_email",
        ),
        migrations.RenameField(
            model_name="donation",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="message_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="donation_id",
            new_name="donation",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="organizationadmin",
            old_name="admin_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="organizationadmin",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="userreview",
            old_name="review_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="userreview",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_received_messages",
                to="database.organization",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="receiver_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_sent_messages",
                to="database.organization",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationadmin",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
