# Generated by Django 5.1.1 on 2024-10-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_populate_user_profiles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="id",
            new_name="message_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="id",
            new_name="order_id",
        ),
        migrations.RenameField(
            model_name="organizationadmin",
            old_name="id",
            new_name="admin_id",
        ),
        migrations.RenameField(
            model_name="userreview",
            old_name="id",
            new_name="userreview_id",
        ),
    ]
