# Generated by Django 5.1.1 on 2024-10-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_rename_id_message_message_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userreview",
            old_name="userreview_id",
            new_name="review_id",
        ),
    ]
