# Generated by Django 5.1.1 on 2024-10-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_rename_userreview_id_userreview_review_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreview",
            name="organization",
        ),
        migrations.AddField(
            model_name="userreview",
            name="donation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.donation",
            ),
        ),
    ]
