# Generated by Django 5.1.1 on 2024-11-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0010_room_conversor_1_name_room_conversor_2_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="image_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
