# Generated by Django 5.1.1 on 2024-11-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_communitydrive_driveorganization_drivevolunteer"),
        ("database", "0011_donation_image_data"),
    ]

    operations = []
