# Generated by Django 5.1.1 on 2024-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0012_merge_20241125_2312"),
    ]

    operations = [
        migrations.AddField(
            model_name="driveorganization",
            name="volunteer_pledge",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="driveorganization",
            name="meal_pledge",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="DriveVolunteer",
        ),
    ]
