language: python
dist: bionic
os: linux
python:
  - "3.11"

install:
  - pip install -r requirements.txt

script:
  - black --check ./src
  - flake8 ./src
  - djlint src/ --lint        
  - coverage run --source='src' src/manage.py test src
  - coverage report
  - coveralls
  - python src/manage.py makemigrations
  - python src/manage.py migrate
  - python src/manage.py collectstatic --noinput
  
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "wed-fall24-team5"
    env: "food-donation-swe-dev"
    bucket_name: "elasticbeanstalk-us-east-1-149536460878"
    on:
      repo: gcivil-nyu-org/wed-fall24-team5
      branch: develop
    
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "wed-fall24-team5"
    env: "food-donation-swe-prod"
    bucket_name: "elasticbeanstalk-us-east-1-149536460878"
    on:
      repo: gcivil-nyu-org/wed-fall24-team5
      branch: main
